// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/abstractions.dart';
import 'api/inference.dart';
import 'api/postprocessing.dart';
import 'api/preprocessing.dart';
import 'api/utils.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ArrayF32Ix4Ptr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ArrayF32IxDynPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn;

  @protected
  ArrayF32Ix4
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          dynamic raw);

  @protected
  ArrayF32IxDyn
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          dynamic raw);

  @protected
  ArrayF32Ix4
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          dynamic raw);

  @protected
  ArrayF32IxDyn
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BoundingBox dco_decode_TraitDef_BoundingBox(dynamic raw);

  @protected
  XYWHn dco_decode_box_autoadd_xyw_hn(dynamic raw);

  @protected
  XYWH dco_decode_box_autoadd_xywh(dynamic raw);

  @protected
  XYXYn dco_decode_box_autoadd_xyx_yn(dynamic raw);

  @protected
  XYXY dco_decode_box_autoadd_xyxy(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(double, double, double, double, BigInt, double)>
      dco_decode_list_record_f_32_f_32_f_32_f_32_usize_f_32(dynamic raw);

  @protected
  (
    ArrayF32Ix4,
    int,
    int
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arrayf_32_ix_4_u_32_u_32(
      dynamic raw);

  @protected
  (double, double, double, double, BigInt, double)
      dco_decode_record_f_32_f_32_f_32_f_32_usize_f_32(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  XYWHn dco_decode_xyw_hn(dynamic raw);

  @protected
  XYWH dco_decode_xywh(dynamic raw);

  @protected
  XYXYn dco_decode_xyx_yn(dynamic raw);

  @protected
  XYXY dco_decode_xyxy(dynamic raw);

  @protected
  ArrayF32Ix4
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          SseDeserializer deserializer);

  @protected
  ArrayF32IxDyn
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          SseDeserializer deserializer);

  @protected
  ArrayF32Ix4
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          SseDeserializer deserializer);

  @protected
  ArrayF32IxDyn
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  XYWHn sse_decode_box_autoadd_xyw_hn(SseDeserializer deserializer);

  @protected
  XYWH sse_decode_box_autoadd_xywh(SseDeserializer deserializer);

  @protected
  XYXYn sse_decode_box_autoadd_xyx_yn(SseDeserializer deserializer);

  @protected
  XYXY sse_decode_box_autoadd_xyxy(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(double, double, double, double, BigInt, double)>
      sse_decode_list_record_f_32_f_32_f_32_f_32_usize_f_32(
          SseDeserializer deserializer);

  @protected
  (
    ArrayF32Ix4,
    int,
    int
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arrayf_32_ix_4_u_32_u_32(
      SseDeserializer deserializer);

  @protected
  (double, double, double, double, BigInt, double)
      sse_decode_record_f_32_f_32_f_32_f_32_usize_f_32(
          SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  XYWHn sse_decode_xyw_hn(SseDeserializer deserializer);

  @protected
  XYWH sse_decode_xywh(SseDeserializer deserializer);

  @protected
  XYXYn sse_decode_xyx_yn(SseDeserializer deserializer);

  @protected
  XYXY sse_decode_xyxy(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          ArrayF32Ix4 self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          ArrayF32IxDyn self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          ArrayF32Ix4 self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          ArrayF32IxDyn self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_xyw_hn(XYWHn self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_xywh(XYWH self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_xyx_yn(XYXYn self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_xyxy(XYXY self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_f_32_f_32_f_32_f_32_usize_f_32(
      List<(double, double, double, double, BigInt, double)> self,
      SseSerializer serializer);

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arrayf_32_ix_4_u_32_u_32(
          (ArrayF32Ix4, int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_record_f_32_f_32_f_32_f_32_usize_f_32(
      (double, double, double, double, BigInt, double) self,
      SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_xyw_hn(XYWHn self, SseSerializer serializer);

  @protected
  void sse_encode_xywh(XYWH self, SseSerializer serializer);

  @protected
  void sse_encode_xyx_yn(XYXYn self, SseSerializer serializer);

  @protected
  void sse_encode_xyxy(XYXY self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32Ix4(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArrayf32IxDyn(
          int ptr);
}
