// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `area`, `intersect`, `iou`
// These types are ignored because they are not used by any `pub` functions: `ProbSpace`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class XYXYBBox {
  final double x1;
  final double y1;
  final double x2;
  final double y2;
  final double probability;
  final String label;

  const XYXYBBox({
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
    required this.probability,
    required this.label,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<XYXYBBox> newInstance(
          {required double x1,
          required double y1,
          required double x2,
          required double y2,
          required double probability,
          required String label}) =>
      RustLib.instance.api.crateApiAbstractionsXyxybBoxNew(
          x1: x1,
          y1: y1,
          x2: x2,
          y2: y2,
          probability: probability,
          label: label);

  @override
  int get hashCode =>
      x1.hashCode ^
      y1.hashCode ^
      x2.hashCode ^
      y2.hashCode ^
      probability.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XYXYBBox &&
          runtimeType == other.runtimeType &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          x2 == other.x2 &&
          y2 == other.y2 &&
          probability == other.probability &&
          label == other.label;
}
