// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'abstractions.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `import_model`, `run_model`

Future<void> setModel(
        {required String value,
        required int newInputWidth,
        required int newInputHeight}) =>
    RustLib.instance.api.crateApiInferenceSetModel(
        value: value,
        newInputWidth: newInputWidth,
        newInputHeight: newInputHeight);

Future<List<XYXY>> detect({required String filePath}) =>
    RustLib.instance.api.crateApiInferenceDetect(filePath: filePath);
