// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'abstractions.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `intersection`, `iou`, `union`

Future<List<XYXY>> processOutput(
        {required ArrayF32IxDyn output,
        required int imgWidth,
        required int imgHeight,
        required int inputWidth,
        required int inputHeight}) =>
    RustLib.instance.api.crateApiPostprocessingProcessOutput(
        output: output,
        imgWidth: imgWidth,
        imgHeight: imgHeight,
        inputWidth: inputWidth,
        inputHeight: inputHeight);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Array < f32 , IxDyn >>>
abstract class ArrayF32IxDyn implements RustOpaqueInterface {}
