#[derive(PartialEq)]
pub enum Lang {
    EN,
    ES,
    FR,
    DE,
    ZH,
    JA,
    PT,
    VI,
    NK,
}

impl Default for Lang {
    fn default() -> Self {
        let locale = sys_locale::get_locale().unwrap_or_default();
        let lang_code = locale.get(0..2).unwrap_or("en");
        Self::from_str(lang_code)
    }
}

impl Lang {
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "en" => Lang::EN,
            "es" => Lang::ES,
            "fr" => Lang::FR,
            "de" => Lang::DE,
            "zh" => Lang::ZH,
            "ja" => Lang::JA,
            "pt" => Lang::PT,
            "vi" => Lang::VI,
            "bs" | "hr" | "sr" => Lang::NK,
            _ => Lang::EN,
        }
    }

    pub fn from_optional_str(s: Option<&str>) -> Self {
        match s {
            Some(code) => Self::from_str(code),
            None => Lang::default(),
        }
    }
}

pub const LANGUAGES: [(Lang, &'static str); 9] = [
    (Lang::EN, "English"),
    (Lang::ES, "Español"),
    (Lang::FR, "Français"),
    (Lang::DE, "Deutsch"),
    (Lang::ZH, "简体中文"),
    (Lang::JA, "日本語"),
    (Lang::PT, "Português"),
    (Lang::VI, "Tiếng Việt"),
    (Lang::NK, "Naški"),
];

#[allow(non_camel_case_types)]
pub enum Key {
    select_ai,
    select_ep,
    setup,
    deploy,
    deployed_api,
    select_your_data,
    folder,
    image,
    video_file,
    camera_feed,
    about,
    idiom,
    models,
    source_code,
    analyze,
    export,
    analysis,
    cancel,
    done,
    error_ocurred,
    model_hub,
    api,
    image_processing,
    video_processing,
    feed_processing,
    model_hub_url,
    export_predictions,
    export_imgs_with_predictions,
    input_url,
    example,
    freq,
    ok,
    no_predictions,
    add_classification_model_to_complement,
    configure_ai,
    confidence_level,
    overlap_filter,
    region_filter,
    yes,
    no_only_missing_data,
    process_everything,
    export_obs,
    deployed_api_allows,
    select_2nd_ai,
    no_api_running,
    select_model_and_deploy,
    api_live,
    deploy_api,
    nav_hint,
    select_hint,
    loaded,
    focus_deploy_to_reveal_ip,
    audio_file,
    position,
    window,
    width_,
    height_,
    export_video_with_predictions,
    saved_to,
    saved_next_to_originals,
    unknown_file,
    not_analysed,
    not_analysed_parens,
    predictions,
    classification,
    refined,
    detection,
    detections,
    segment,
    segments,
    no_ai,
    and_more_fmt,
    confidence_pct,
    analysing,
    reset_playhead,
    fit,
    fit_view_hint,
    cache_secs,
    stream_feed_hint,
    pause,
    live,
    live_hint,
    prev,
    next,
    export_current_frame_json,
    export_current_frame_png,
    frame_no_ai_data,
    analyze_this_image,
    analyze_this_image_hint,
    play,
    frames_analysed,
    view_label,
    span_label,
    buffer_label,
    audio_processing,
    frame_label,
}

pub fn translate(key: Key, lang: &Lang) -> &'static str {
    match key {
        Key::select_ai => match lang {
            Lang::EN => "AI",
            Lang::ES => "IA",
            Lang::FR => "IA",
            Lang::DE => "KI",
            Lang::ZH => "选择AI模型",
            Lang::JA => "AIを選択",
            Lang::PT => "IA",
            Lang::VI => "Lựa chọn AI",
            Lang::NK => "AI",
        },
        Key::select_2nd_ai => match lang {
            Lang::EN => "Classification AI",
            Lang::ES => "IA de clasificación",
            Lang::FR => "IA de classification",
            Lang::DE => "Klassifizierungs-KI",
            Lang::ZH => "分类AI",
            Lang::JA => "分類AI",
            Lang::PT => "IA de classificação",
            Lang::VI => "AI phân loại",
            Lang::NK => "AI za klasifikaciju",
        },
        Key::deployed_api_allows => match lang {
            Lang::EN => "Allows devices on your local network to connect to this BoquilaHUB instance and use your computer for processing",
            Lang::ES => "Permite que los dispositivos de tu red local se conecten a esta instancia de BoquilaHUB y usen tu computadora para el procesamiento",
            Lang::FR => "Permet aux appareils de votre réseau local de se connecter à cette instance de BoquilaHUB et d'utiliser votre ordinateur pour le traitement",
            Lang::DE => "Ermöglicht Geräten in Ihrem lokalen Netzwerk, sich mit dieser BoquilaHUB-Instanz zu verbinden und Ihren Computer zur Verarbeitung zu verwenden",
            Lang::ZH => "允许本地网络中的设备连接到此 BoquilaHUB 实例并使用你的计算机进行处理",
            Lang::JA => "ローカルネットワーク上のデバイスがこのBoquilaHUBインスタンスに接続し、あなたのコンピュータを処理に使用できるようにします",
            Lang::PT => "Permite que dispositivos na sua rede local se conectem a esta instância do BoquilaHUB e usem o seu computador para processamento",
            Lang::VI => "Cho phép các thiết bị trong mạng cục bộ kết nối với BoquilaHUB này và sử dụng máy tính của bạn để xử lý",
            Lang::NK => "Omogućava uređajima na vašoj lokalnoj mreži da se povežu na ovu BoquilaHUB instancu i koriste vaš računar za obradu",
        }
        Key::yes => match lang {
            Lang::EN => "Yes",
            Lang::ES => "Sí",
            Lang::FR => "Oui",
            Lang::DE => "Ja",
            Lang::ZH => "是",
            Lang::JA => "はい",
            Lang::PT => "Sim",
            Lang::VI => "Đồng ý",
            Lang::NK => "Da",
        },
        Key::no_only_missing_data => match lang {
            Lang::EN => "No, only missing data",
            Lang::ES => "No, solo los datos faltantes",
            Lang::FR => "Non, seulement les données manquantes",
            Lang::DE => "Nein, nur fehlende Daten",
            Lang::ZH => "不，只处理缺失的数据",
            Lang::JA => "いいえ、不足しているデータのみ",
            Lang::PT => "Não, apenas os dados em falta",
            Lang::VI => "Không, chỉ khi dữ liệu bị thiếu",
            Lang::NK => "Ne, samo nedostajuće podatke",
        },
        Key::process_everything => match lang {
            Lang::EN => "Process everything?",
            Lang::ES => "¿Procesar todo?",
            Lang::FR => "Tout traiter ?",
            Lang::DE => "Alles verarbeiten?",
            Lang::ZH => "处理所有内容？",
            Lang::JA => "すべて処理しますか？",
            Lang::PT => "Processar tudo?",
            Lang::VI => "Xử lí mọi thứ?",
            Lang::NK => "Obraditi sve?",
        },
        Key::confidence_level => match lang {
            Lang::EN => "Confidence",
            Lang::ES => "Confianza",
            Lang::FR => "Confiance",
            Lang::DE => "Genauigkeit",
            Lang::ZH => "置信度",
            Lang::JA => "信頼度",
            Lang::PT => "Confiança",
            Lang::VI => "Độ tin cậy của mô hình",
            Lang::NK => "Pouzdanost",
        },
        Key::overlap_filter => match lang {
            Lang::EN => "Overlap Filter",
            Lang::ES => "Filtro de Solapamiento",
            Lang::FR => "Filtre de Chevauchement",
            Lang::DE => "Überlappungsfilter",
            Lang::ZH => "重叠过滤",
            Lang::JA => "重複フィルター",
            Lang::PT => "Filtro de Sobreposição",
            Lang::VI => "Bộ lọc trùng lặp",
            Lang::NK => "Filter preklapanja",
        },
        Key::region_filter => match lang {
            Lang::EN => "Region (ISO 3166-1 alpha-3)",
            Lang::ES => "Región (ISO 3166-1 alpha-3)",
            Lang::FR => "Région (ISO 3166-1 alpha-3)",
            Lang::DE => "Region (ISO 3166-1 alpha-3)",
            Lang::ZH => "区域 (ISO 3166-1 alpha-3)",
            Lang::JA => "地域 (ISO 3166-1 alpha-3)",
            Lang::PT => "Região (ISO 3166-1 alpha-3)",
            Lang::VI => "Mã quốc gia (ISO 3166-1 alpha-3)",
            Lang::NK => "Region (ISO 3166-1 alpha-3)",
        },
        Key::configure_ai => match lang {
            Lang::EN => "Configure AI",
            Lang::ES => "Configurar IA",
            Lang::FR => "Configurer l'IA",
            Lang::DE => "KI konfigurieren",
            Lang::ZH => "配置AI",
            Lang::JA => "AIを設定",
            Lang::PT => "Configurar IA",
            Lang::VI => "Cấu hình AI",
            Lang::NK => "Podesi AI",
        },
        Key::add_classification_model_to_complement => match lang {
            Lang::EN => "Add a classification AI to complement the current model",
            Lang::ES => "Agregar una IA de clasificación para complementar el modelo actual",
            Lang::FR => "Ajouter une IA de classification pour compléter le modèle actuel",
            Lang::DE => "Eine Klassifikations-KI hinzufügen, um das aktuelle Modell zu ergänzen",
            Lang::ZH => "添加分类AI以补充当前模型",
            Lang::JA => "現在のモデルを補完する分類AIを追加",
            Lang::PT => "Adicionar uma IA de classificação para complementar o modelo atual",
            Lang::VI => "Bổ sung một mô hình AI phân loại để hỗ trợ mô hình hiện tại",
            Lang::NK => "Dodaj AI za klasifikaciju da dopuni trenutni model",
        },
        Key::select_ep => match lang {
            Lang::EN => "Processor",
            Lang::ES => "Procesador",
            Lang::FR => "Processeur",
            Lang::DE => "Prozessor",
            Lang::ZH => "选择处理器",
            Lang::JA => "プロセッサーを選択",
            Lang::PT => "Processador",
            Lang::VI => "Chọn bộ xử lí",
            Lang::NK => "Procesor",
        },
        Key::setup => match lang {
            Lang::EN => "Setup",
            Lang::ES => "Configuración",
            Lang::FR => "Configuration",
            Lang::DE => "Einrichtung",
            Lang::ZH => "配置",
            Lang::JA => "セットアップ",
            Lang::PT => "Configuração",
            Lang::VI => "Thiết lập mô hình",
            Lang::NK => "Podešavanje",
        },
        Key::no_predictions => match lang {
            Lang::EN => "No predictions",
            Lang::ES => "Sin predicciones",
            Lang::FR => "Aucune prédiction",
            Lang::DE => "Keine Vorhersagen",
            Lang::ZH => "没有预测",
            Lang::JA => "予測なし",
            Lang::PT => "Sem previsões",
            Lang::VI => "Không tìm thấy kết quả dự đoán",
            Lang::NK => "Nema predviđanja",
        },
        Key::deploy => match lang {
            Lang::EN => "Deploy",
            Lang::ES => "Desplegar",
            Lang::FR => "Déployer",
            Lang::DE => "Bereitstellen",
            Lang::ZH => "部署",
            Lang::JA => "デプロイ",
            Lang::PT => "Implantar",
            Lang::VI => "Triển khai",
            Lang::NK => "Pokreni",
        },
        Key::deployed_api => match lang {
            Lang::EN => "Deployed API",
            Lang::ES => "API desplegada",
            Lang::FR => "API déployée",
            Lang::DE => "Bereitgestellte API",
            Lang::ZH => "已部署API",
            Lang::JA => "デプロイ済みAPI",
            Lang::PT => "API implantada",
            Lang::VI => "Triển khai API",
            Lang::NK => "Pokrenuti API",
        },
        Key::select_your_data => match lang {
            Lang::EN => "Select your data",
            Lang::ES => "Selecciona tus datos",
            Lang::FR => "Sélectionnez vos données",
            Lang::DE => "Wählen Sie Ihre Daten aus",
            Lang::ZH => "选取数据",
            Lang::JA => "データを選択",
            Lang::PT => "Selecionar os seus dados",
            Lang::VI => "Chọn dữ liệu của bạn",
            Lang::NK => "Izaberi podatke",
        },
        Key::folder => match lang {
            Lang::EN => "Folder",
            Lang::ES => "Carpeta",
            Lang::FR => "Dossier",
            Lang::DE => "Ordner",
            Lang::ZH => "文件夹",
            Lang::JA => "フォルダ",
            Lang::PT => "Pasta",
            Lang::VI => "Thư mục",
            Lang::NK => "Folder",
        },
        Key::image => match lang {
            Lang::EN => "Image",
            Lang::ES => "Imagen",
            Lang::FR => "Image",
            Lang::DE => "Bild",
            Lang::ZH => "图片",
            Lang::JA => "画像",
            Lang::PT => "Imagem",
            Lang::VI => "Hình ảnh",
            Lang::NK => "Slika",
        },
        Key::video_file => match lang {
            Lang::EN => "Video",
            Lang::ES => "Video",
            Lang::FR => "Vidéo",
            Lang::DE => "Video",
            Lang::ZH => "视频",
            Lang::JA => "ビデオ",
            Lang::PT => "Vídeo",
            Lang::VI => "Video",
            Lang::NK => "Video",
        },
        Key::camera_feed => match lang {
            Lang::EN => "Feed",
            Lang::ES => "Cámara",
            Lang::FR => "Flux",
            Lang::DE => "Kamerafeed",
            Lang::ZH => "视频流",
            Lang::JA => "カメラフィード",
            Lang::PT => "Transmissão",
            Lang::VI => "Nguồn khác",
            Lang::NK => "Kamera",
        },
        Key::about => match lang {
            Lang::EN => "About",
            Lang::ES => "Información",
            Lang::FR => "À propos",
            Lang::DE => "Über",
            Lang::ZH => "关于",
            Lang::JA => "情報",
            Lang::PT => "Sobre",
            Lang::VI => "Thông tin",
            Lang::NK => "Info",
        },
        Key::idiom => match lang {
            Lang::EN => "Language",
            Lang::ES => "Idioma",
            Lang::FR => "Langue",
            Lang::DE => "Sprache",
            Lang::ZH => "语言",
            Lang::JA => "言語",
            Lang::PT => "Idioma",
            Lang::VI => "Ngôn ngữ",
            Lang::NK => "Jezik",
        },
        Key::models => match lang {
            Lang::EN => "Models",
            Lang::ES => "Modelos",
            Lang::FR => "Modèles",
            Lang::DE => "Modelle",
            Lang::ZH => "模型",
            Lang::JA => "モデル",
            Lang::PT => "Modelos",
            Lang::VI => "Mô hình",
            Lang::NK => "Modeli",
        },
        Key::source_code => match lang {
            Lang::EN => "Source code",
            Lang::ES => "Código fuente",
            Lang::FR => "Code source",
            Lang::DE => "Quellcode",
            Lang::ZH => "源代码",
            Lang::JA => "ソースコード",
            Lang::PT => "Código-fonte",
            Lang::VI => "Mã nguồn",
            Lang::NK => "Izvorni kod",
        },
        Key::analyze => match lang {
            Lang::EN => "Analyze",
            Lang::ES => "Analizar",
            Lang::FR => "Analyser",
            Lang::DE => "Analysieren",
            Lang::ZH => "开始分析",
            Lang::JA => "解析する",
            Lang::PT => "Analisar",
            Lang::VI => "Xử lí",
            Lang::NK => "Analiziraj",
        },
        Key::export => match lang {
            Lang::EN => "Export",
            Lang::ES => "Exportar",
            Lang::FR => "Exporter",
            Lang::DE => "Exportieren",
            Lang::ZH => "导出",
            Lang::JA => "エクスポート",
            Lang::PT => "Exportar",
            Lang::VI => "Xuất kết quả",
            Lang::NK => "Izvezi",
        },
        Key::analysis => match lang {
            Lang::EN => "Analysis",
            Lang::ES => "Análisis",
            Lang::FR => "Analyse",
            Lang::DE => "Analyse",
            Lang::ZH => "分析",
            Lang::JA => "解析",
            Lang::PT => "Análise",
            Lang::VI => "Phân tích",
            Lang::NK => "Analiza",
        },
        Key::cancel => match lang {
            Lang::EN => "Cancel",
            Lang::ES => "Cancelar",
            Lang::FR => "Annuler",
            Lang::DE => "Abbrechen",
            Lang::ZH => "取消",
            Lang::JA => "キャンセル",
            Lang::PT => "Cancelar",
            Lang::VI => "Hủy bỏ",
            Lang::NK => "Otkaži",
        },
        Key::ok => match lang {
            Lang::EN => "OK",
            Lang::ES => "Aceptar",
            Lang::FR => "OK",
            Lang::DE => "OK",
            Lang::ZH => "确定",
            Lang::JA => "OK",
            Lang::PT => "OK",
            Lang::VI => "OK",
            Lang::NK => "OK",
        },
        
        Key::done => match lang {
            Lang::EN => "✅ Done",
            Lang::ES => "✅ Listo",
            Lang::FR => "✅ Terminé",
            Lang::DE => "✅ Fertig",
            Lang::ZH => "✅ 已完成",
            Lang::JA => "✅ 完了",
            Lang::PT => "✅ Concluído",
            Lang::VI => "✅ Hoàn tất",
            Lang::NK => "✅ Gotovo",
        },
        Key::error_ocurred => match lang {
            Lang::EN => "Error occurred",
            Lang::ES => "Ocurrió un error",
            Lang::FR => "Une erreur est survenue",
            Lang::DE => "Ein Fehler ist aufgetreten",
            Lang::ZH => "发生错误",
            Lang::JA => "エラーが発生しました",
            Lang::PT => "Ocorreu um erro",
            Lang::VI => "Đã có lỗi xảy ra",
            Lang::NK => "Došlo je do greške",
        },
        Key::model_hub => match lang {
            Lang::EN => "Model HUB",
            Lang::ES => "HUB de Modelos",
            Lang::FR => "HUB de Modèles",
            Lang::DE => "Modell-HUB",
            Lang::ZH => "模型库",
            Lang::JA => "モデルハブ",
            Lang::PT => "Central de Modelos",
            Lang::VI => "Model Hub",
            Lang::NK => "Model HUB",
        },
        Key::api => match lang {
            _ => "API",
        },
        Key::image_processing => match lang {
            Lang::EN => "Images processing",
            Lang::ES => "Procesamiento de imágenes",
            Lang::FR => "Traitement d'images",
            Lang::DE => "Bildverarbeitung",
            Lang::ZH => "图片处理中",
            Lang::JA => "画像を処理中",
            Lang::PT => "Processando imagens",
            Lang::VI => "Xử lí hình ảnh",
            Lang::NK => "Obrada slika",
        },
        Key::video_processing => match lang {
            Lang::EN => "Video processing",
            Lang::ES => "Procesamiento de video",
            Lang::FR => "Traitement vidéo",
            Lang::DE => "Videoverarbeitung",
            Lang::ZH => "视频处理中",
            Lang::JA => "ビデオ処理中",
            Lang::PT => "Processando vídeo",
            Lang::VI => "Xử lí video",
            Lang::NK => "Obrada videa",
        },
        Key::feed_processing => match lang {
            Lang::EN => "Feed processing",
            Lang::ES => "Procesamiento en vivo",
            Lang::FR => "Traitement en direct",
            Lang::DE => "Live-Verarbeitung",
            Lang::ZH => "视频流处理中",
            Lang::JA => "フィード処理中",
            Lang::PT => "Processando transmissão",
            Lang::VI => "Xử lí dữ liệu khác",
            Lang::NK => "Obrada prenosa",
        },
        Key::model_hub_url => match lang {
            Lang::EN => "https://boquila.org/hub",
            Lang::ES => "https://boquila.org/es/hub",
            Lang::FR => "https://boquila.org/fr/hub",
            Lang::DE => "https://boquila.org/de/hub",
            Lang::ZH => "https://boquila.org/zh/hub",
            Lang::JA => "https://boquila.org/ja/hub",
            _ => "https://boquila.org/hub",
        },
        Key::export_predictions => match lang {
            Lang::EN => "Export predictions (.json)",
            Lang::ES => "Exportar predicciones (.json)",
            Lang::FR => "Exporter les prédictions (.json)",
            Lang::DE => "Vorhersagen exportieren (.json)",
            Lang::ZH => "导出识别结果（.json）",
            Lang::JA => "予測をエクスポート（.json）",
            Lang::PT => "Exportar previsões (.json)",
            Lang::VI => "Xuất kết quả (.json)",
            Lang::NK => "Izvezi predviđanja (.json)",
        },
        Key::export_imgs_with_predictions => match lang {
            Lang::EN => "Export images with predictions (.jpg)",
            Lang::ES => "Exportar imágenes con predicciones (.jpg)",
            Lang::FR => "Exporter les images avec prédictions (.jpg)",
            Lang::DE => "Bilder mit Vorhersagen exportieren (.jpg)",
            Lang::ZH => "导出含识别结果的图片（.jpg）",
            Lang::JA => "予測付き画像をエクスポート（.jpg）",
            Lang::PT => "Exportar imagens com previsões (.jpg)",
            Lang::VI => "Xuất kết quả (.jpg)",
            Lang::NK => "Izvezi slike sa predviđanjima (.jpg)",
        },
        Key::input_url => match lang {
            Lang::EN => "Add the URL",
            Lang::ES => "Ingresa la dirección URL",
            Lang::FR => "Ajoutez l'URL",
            Lang::DE => "URL hinzufügen",
            Lang::ZH => "输入视频流地址（URL）",
            Lang::JA => "URLを追加",
            Lang::PT => "Adicionar o URL",
            Lang::VI => "Nhập URL",
            Lang::NK => "Unesi URL",
        },
        Key::example => match lang {
            Lang::EN => "Example",
            Lang::ES => "Ejemplo",
            Lang::FR => "Exemple",
            Lang::DE => "Beispiel",
            Lang::ZH => "示例",
            Lang::JA => "例",
            Lang::PT => "Exemplo",
            Lang::VI => "Mẫu",
            Lang::NK => "Primer",
        },
        Key::freq => match lang {
            Lang::EN => "Frequency",
            Lang::ES => "Frecuencia",
            Lang::FR => "Fréquence",
            Lang::DE => "Frequenz",
            Lang::ZH => "频率",
            Lang::JA => "頻度",
            Lang::PT => "Frequência",
            Lang::VI => "Tần suất",
            Lang::NK => "Frekvencija",
        },
        Key::export_obs => match lang {
            Lang::EN => "Export detections",
            Lang::ES => "Exportar detecciones",
            Lang::FR => "Exporter détections",
            Lang::DE => "Erkennungen exportieren",
            Lang::ZH => "导出检测",
            Lang::JA => "検出をエクスポート",
            Lang::PT => "Exportar detecções",
            Lang::VI => "Trích xuất kết quả phát hiện",
            Lang::NK => "Izvezi detekcije",
        },
        Key::no_api_running => match lang {
            Lang::EN => "No API running",
            Lang::ES => "No hay API en ejecución",
            Lang::FR => "Aucune API en cours",
            Lang::DE => "Keine API aktiv",
            Lang::ZH => "没有运行中的API",
            Lang::JA => "APIが実行されていません",
            Lang::PT => "Nenhuma API em execução",
            Lang::VI => "Chưa có API nào đang chạy",
            Lang::NK => "Nema pokrenutog API-ja",
        },
        Key::select_model_and_deploy => match lang {
            Lang::EN => "Select a model and deploy",
            Lang::ES => "Selecciona un modelo y despliega",
            Lang::FR => "Sélectionnez un modèle et déployez",
            Lang::DE => "Modell auswählen und bereitstellen",
            Lang::ZH => "选择模型并部署",
            Lang::JA => "モデルを選択してデプロイ",
            Lang::PT => "Selecione um modelo e implante",
            Lang::VI => "Chọn mô hình và triển khai",
            Lang::NK => "Izaberi model i pokreni",
        },
        Key::api_live => match lang {
            Lang::EN => "● API Live",
            Lang::ES => "● API activa",
            Lang::FR => "● API active",
            Lang::DE => "● API aktiv",
            Lang::ZH => "● API 运行中",
            Lang::JA => "● API稼働中",
            Lang::PT => "● API ativa",
            Lang::VI => "● API đang chạy",
            Lang::NK => "● API aktivan",
        },
        Key::deploy_api => match lang {
            Lang::EN => "Deploy API",
            Lang::ES => "Desplegar API",
            Lang::FR => "Déployer l'API",
            Lang::DE => "API bereitstellen",
            Lang::ZH => "部署API",
            Lang::JA => "APIをデプロイ",
            Lang::PT => "Implantar API",
            Lang::VI => "Triển khai API",
            Lang::NK => "Pokreni API",
        },
        Key::nav_hint => match lang {
            Lang::EN => "nav",
            Lang::ES => "nav",
            Lang::FR => "nav",
            Lang::DE => "Nav",
            Lang::ZH => "导航",
            Lang::JA => "移動",
            Lang::PT => "nav",
            Lang::VI => "di chuyển",
            Lang::NK => "kretanje",
        },
        Key::select_hint => match lang {
            Lang::EN => "select",
            Lang::ES => "elegir",
            Lang::FR => "choisir",
            Lang::DE => "wählen",
            Lang::ZH => "选择",
            Lang::JA => "選択",
            Lang::PT => "escolher",
            Lang::VI => "chọn",
            Lang::NK => "izaberi",
        },
        Key::loaded => match lang {
            Lang::EN => "Loaded",
            Lang::ES => "Cargado",
            Lang::FR => "Chargé",
            Lang::DE => "Geladen",
            Lang::ZH => "已加载",
            Lang::JA => "読み込み済み",
            Lang::PT => "Carregado",
            Lang::VI => "Đã tải",
            Lang::NK => "Učitano",
        },
        Key::focus_deploy_to_reveal_ip => match lang {
            Lang::EN => "▸ focus Deploy to reveal IP",
            Lang::ES => "▸ enfoca Desplegar para ver la IP",
            Lang::FR => "▸ sélectionnez Déployer pour voir l'IP",
            Lang::DE => "▸ Bereitstellen fokussieren für IP",
            Lang::ZH => "▸ 聚焦部署以显示IP",
            Lang::JA => "▸ デプロイを選択してIPを表示",
            Lang::PT => "▸ foque em Implantar para ver o IP",
            Lang::VI => "▸ chọn Triển khai để xem IP",
            Lang::NK => "▸ fokusiraj Pokreni da prikažeš IP",
        },
        Key::audio_file => match lang {
            Lang::EN => "Audio",
            Lang::ES => "Audio",
            Lang::FR => "Audio",
            Lang::DE => "Audio",
            Lang::ZH => "音频",
            Lang::JA => "オーディオ",
            Lang::PT => "Áudio",
            Lang::VI => "Âm thanh",
            Lang::NK => "Audio",
        },
        Key::position => match lang {
            Lang::EN => "position (s)",
            Lang::ES => "posición (s)",
            Lang::FR => "position (s)",
            Lang::DE => "Position (s)",
            Lang::ZH => "位置 (秒)",
            Lang::JA => "位置 (秒)",
            Lang::PT => "posição (s)",
            Lang::VI => "vị trí (giây)",
            Lang::NK => "pozicija (s)",
        },
        Key::window => match lang {
            Lang::EN => "window (s)",
            Lang::ES => "ventana (s)",
            Lang::FR => "fenêtre (s)",
            Lang::DE => "Fenster (s)",
            Lang::ZH => "窗口 (秒)",
            Lang::JA => "ウィンドウ (秒)",
            Lang::PT => "janela (s)",
            Lang::VI => "cửa sổ (giây)",
            Lang::NK => "prozor (s)",
        },
        Key::width_ => match lang {
            Lang::EN => "width",
            Lang::ES => "ancho",
            Lang::FR => "largeur",
            Lang::DE => "Breite",
            Lang::ZH => "宽度",
            Lang::JA => "幅",
            Lang::PT => "largura",
            Lang::VI => "chiều rộng",
            Lang::NK => "širina",
        },
        Key::height_ => match lang {
            Lang::EN => "height",
            Lang::ES => "alto",
            Lang::FR => "hauteur",
            Lang::DE => "Höhe",
            Lang::ZH => "高度",
            Lang::JA => "高さ",
            Lang::PT => "altura",
            Lang::VI => "chiều cao",
            Lang::NK => "visina",
        },
        Key::export_video_with_predictions => match lang {
            Lang::EN => "Export video with predictions (.mp4)",
            Lang::ES => "Exportar video con predicciones (.mp4)",
            Lang::FR => "Exporter la vidéo avec prédictions (.mp4)",
            Lang::DE => "Video mit Vorhersagen exportieren (.mp4)",
            Lang::ZH => "导出含识别结果的视频（.mp4）",
            Lang::JA => "予測付き動画をエクスポート（.mp4）",
            Lang::PT => "Exportar vídeo com previsões (.mp4)",
            Lang::VI => "Xuất video kèm dự đoán (.mp4)",
            Lang::NK => "Izvezi video sa predviđanjima (.mp4)",
        },
        Key::saved_to => match lang {
            Lang::EN => "Saved to",
            Lang::ES => "Guardado en",
            Lang::FR => "Enregistré dans",
            Lang::DE => "Gespeichert in",
            Lang::ZH => "已保存至",
            Lang::JA => "保存先",
            Lang::PT => "Guardado em",
            Lang::VI => "Đã lưu tại",
            Lang::NK => "Sačuvano u",
        },
        Key::saved_next_to_originals => match lang {
            Lang::EN => "Saved next to each source file",
            Lang::ES => "Guardado junto a cada archivo original",
            Lang::FR => "Enregistré à côté de chaque fichier d'origine",
            Lang::DE => "Neben jeder Originaldatei gespeichert",
            Lang::ZH => "已保存到每个源文件旁边",
            Lang::JA => "各元ファイルの隣に保存しました",
            Lang::PT => "Guardado ao lado de cada ficheiro original",
            Lang::VI => "Đã lưu cạnh từng tệp gốc",
            Lang::NK => "Sačuvano pored svake originalne datoteke",
        },
        Key::unknown_file => match lang {
            Lang::EN => "(unknown)",
            Lang::ES => "(desconocido)",
            Lang::FR => "(inconnu)",
            Lang::DE => "(unbekannt)",
            Lang::ZH => "（未知）",
            Lang::JA => "（不明）",
            Lang::PT => "(desconhecido)",
            Lang::VI => "(không xác định)",
            Lang::NK => "(nepoznato)",
        },
        Key::not_analysed => match lang {
            Lang::EN => "not analysed",
            Lang::ES => "sin analizar",
            Lang::FR => "non analysé",
            Lang::DE => "nicht analysiert",
            Lang::ZH => "未分析",
            Lang::JA => "未解析",
            Lang::PT => "não analisado",
            Lang::VI => "chưa phân tích",
            Lang::NK => "neanalizirano",
        },
        Key::not_analysed_parens => match lang {
            Lang::EN => "(not analysed)",
            Lang::ES => "(sin analizar)",
            Lang::FR => "(non analysé)",
            Lang::DE => "(nicht analysiert)",
            Lang::ZH => "（未分析）",
            Lang::JA => "（未解析）",
            Lang::PT => "(não analisado)",
            Lang::VI => "(chưa phân tích)",
            Lang::NK => "(neanalizirano)",
        },
        Key::predictions => match lang {
            Lang::EN => "Predictions",
            Lang::ES => "Predicciones",
            Lang::FR => "Prédictions",
            Lang::DE => "Vorhersagen",
            Lang::ZH => "预测",
            Lang::JA => "予測",
            Lang::PT => "Previsões",
            Lang::VI => "Dự đoán",
            Lang::NK => "Predviđanja",
        },
        Key::classification => match lang {
            Lang::EN => "Classification",
            Lang::ES => "Clasificación",
            Lang::FR => "Classification",
            Lang::DE => "Klassifikation",
            Lang::ZH => "分类",
            Lang::JA => "分類",
            Lang::PT => "Classificação",
            Lang::VI => "Phân loại",
            Lang::NK => "Klasifikacija",
        },
        Key::refined => match lang {
            Lang::EN => "Refined",
            Lang::ES => "Refinado",
            Lang::FR => "Affiné",
            Lang::DE => "Verfeinert",
            Lang::ZH => "精细分类",
            Lang::JA => "詳細分類",
            Lang::PT => "Refinado",
            Lang::VI => "Tinh chỉnh",
            Lang::NK => "Profinjeno",
        },
        Key::detection => match lang {
            Lang::EN => "detection",
            Lang::ES => "detección",
            Lang::FR => "détection",
            Lang::DE => "Erkennung",
            Lang::ZH => "检测",
            Lang::JA => "検出",
            Lang::PT => "detecção",
            Lang::VI => "phát hiện",
            Lang::NK => "detekcija",
        },
        Key::detections => match lang {
            Lang::EN => "detections",
            Lang::ES => "detecciones",
            Lang::FR => "détections",
            Lang::DE => "Erkennungen",
            Lang::ZH => "检测",
            Lang::JA => "検出",
            Lang::PT => "detecções",
            Lang::VI => "phát hiện",
            Lang::NK => "detekcije",
        },
        Key::segment => match lang {
            Lang::EN => "segment",
            Lang::ES => "segmento",
            Lang::FR => "segment",
            Lang::DE => "Segment",
            Lang::ZH => "分段",
            Lang::JA => "セグメント",
            Lang::PT => "segmento",
            Lang::VI => "phân đoạn",
            Lang::NK => "segment",
        },
        Key::segments => match lang {
            Lang::EN => "segments",
            Lang::ES => "segmentos",
            Lang::FR => "segments",
            Lang::DE => "Segmente",
            Lang::ZH => "分段",
            Lang::JA => "セグメント",
            Lang::PT => "segmentos",
            Lang::VI => "phân đoạn",
            Lang::NK => "segmenti",
        },
        Key::no_ai => match lang {
            Lang::EN => "(no AI)",
            Lang::ES => "(sin IA)",
            Lang::FR => "(sans IA)",
            Lang::DE => "(keine KI)",
            Lang::ZH => "（无AI）",
            Lang::JA => "（AIなし）",
            Lang::PT => "(sem IA)",
            Lang::VI => "(không có AI)",
            Lang::NK => "(bez AI)",
        },
        Key::and_more_fmt => match lang {
            Lang::EN => "…and {} more",
            Lang::ES => "…y {} más",
            Lang::FR => "…et {} de plus",
            Lang::DE => "…und {} weitere",
            Lang::ZH => "…还有 {} 个",
            Lang::JA => "…他 {} 件",
            Lang::PT => "…e mais {}",
            Lang::VI => "…và {} nữa",
            Lang::NK => "…i još {}",
        },
        Key::confidence_pct => match lang {
            Lang::EN => "% confidence",
            Lang::ES => "% de confianza",
            Lang::FR => "% de confiance",
            Lang::DE => "% Konfidenz",
            Lang::ZH => "% 置信度",
            Lang::JA => "% の信頼度",
            Lang::PT => "% de confiança",
            Lang::VI => "% độ tin cậy",
            Lang::NK => "% pouzdanost",
        },
        Key::analysing => match lang {
            Lang::EN => "analysing…",
            Lang::ES => "analizando…",
            Lang::FR => "analyse en cours…",
            Lang::DE => "wird analysiert…",
            Lang::ZH => "正在分析…",
            Lang::JA => "解析中…",
            Lang::PT => "a analisar…",
            Lang::VI => "đang phân tích…",
            Lang::NK => "analiziram…",
        },
        Key::reset_playhead => match lang {
            Lang::EN => "Reset playhead to start",
            Lang::ES => "Reiniciar al inicio",
            Lang::FR => "Réinitialiser au début",
            Lang::DE => "Position auf Anfang setzen",
            Lang::ZH => "重置到开始",
            Lang::JA => "再生位置を先頭に戻す",
            Lang::PT => "Reiniciar ao início",
            Lang::VI => "Đặt lại về đầu",
            Lang::NK => "Vrati na početak",
        },
        Key::fit => match lang {
            Lang::EN => "Fit",
            Lang::ES => "Ajustar",
            Lang::FR => "Ajuster",
            Lang::DE => "Anpassen",
            Lang::ZH => "适应",
            Lang::JA => "全体表示",
            Lang::PT => "Ajustar",
            Lang::VI => "Vừa khung",
            Lang::NK => "Uklopi",
        },
        Key::fit_view_hint => match lang {
            Lang::EN => "Fit view to whole audio",
            Lang::ES => "Ajustar vista a todo el audio",
            Lang::FR => "Ajuster la vue à tout l'audio",
            Lang::DE => "Ansicht auf gesamtes Audio anpassen",
            Lang::ZH => "适应整个音频视图",
            Lang::JA => "オーディオ全体を表示",
            Lang::PT => "Ajustar vista ao áudio completo",
            Lang::VI => "Hiển thị toàn bộ âm thanh",
            Lang::NK => "Uklopi prikaz na cijeli audio",
        },
        Key::cache_secs => match lang {
            Lang::EN => "Cache (s)",
            Lang::ES => "Caché (s)",
            Lang::FR => "Cache (s)",
            Lang::DE => "Cache (s)",
            Lang::ZH => "缓存 (秒)",
            Lang::JA => "キャッシュ (秒)",
            Lang::PT => "Cache (s)",
            Lang::VI => "Bộ đệm (giây)",
            Lang::NK => "Keš (s)",
        },
        Key::stream_feed_hint => match lang {
            Lang::EN => "Stream the feed and run AI on every Nth frame",
            Lang::ES => "Transmitir y ejecutar IA cada N cuadros",
            Lang::FR => "Diffuser et exécuter l'IA toutes les N images",
            Lang::DE => "Stream übertragen und KI auf jedes N-te Bild anwenden",
            Lang::ZH => "传输视频流并每隔N帧运行AI",
            Lang::JA => "ストリーミングしてNフレームごとにAIを実行",
            Lang::PT => "Transmitir e executar IA a cada N quadros",
            Lang::VI => "Truyền nguồn và chạy AI mỗi N khung hình",
            Lang::NK => "Prenosi i pokreni AI svakih N kadrova",
        },
        Key::pause => match lang {
            Lang::EN => "Pause",
            Lang::ES => "Pausar",
            Lang::FR => "Pause",
            Lang::DE => "Pause",
            Lang::ZH => "暂停",
            Lang::JA => "一時停止",
            Lang::PT => "Pausar",
            Lang::VI => "Tạm dừng",
            Lang::NK => "Pauza",
        },
        Key::live => match lang {
            Lang::EN => "Live",
            Lang::ES => "En vivo",
            Lang::FR => "Direct",
            Lang::DE => "Live",
            Lang::ZH => "实时",
            Lang::JA => "ライブ",
            Lang::PT => "Ao vivo",
            Lang::VI => "Trực tiếp",
            Lang::NK => "Uživo",
        },
        Key::live_hint => match lang {
            Lang::EN => "Start (or snap to) the live stream",
            Lang::ES => "Iniciar (o saltar a) la transmisión en vivo",
            Lang::FR => "Démarrer (ou aller à) le flux en direct",
            Lang::DE => "Live-Stream starten (oder dorthin springen)",
            Lang::ZH => "开始（或跳至）实时直播",
            Lang::JA => "ライブストリームを開始 (またはジャンプ)",
            Lang::PT => "Iniciar (ou saltar para) a transmissão ao vivo",
            Lang::VI => "Bắt đầu (hoặc nhảy tới) phát trực tiếp",
            Lang::NK => "Pokreni (ili skoči na) uživo prenos",
        },
        Key::prev => match lang {
            Lang::EN => "Previous",
            Lang::ES => "Anterior",
            Lang::FR => "Précédent",
            Lang::DE => "Zurück",
            Lang::ZH => "上一个",
            Lang::JA => "前へ",
            Lang::PT => "Anterior",
            Lang::VI => "Trước",
            Lang::NK => "Prethodno",
        },
        Key::next => match lang {
            Lang::EN => "Next",
            Lang::ES => "Siguiente",
            Lang::FR => "Suivant",
            Lang::DE => "Weiter",
            Lang::ZH => "下一个",
            Lang::JA => "次へ",
            Lang::PT => "Próximo",
            Lang::VI => "Sau",
            Lang::NK => "Sljedeće",
        },
        Key::export_current_frame_json => match lang {
            Lang::EN => "Export current frame (.json)",
            Lang::ES => "Exportar cuadro actual (.json)",
            Lang::FR => "Exporter l'image actuelle (.json)",
            Lang::DE => "Aktuelles Bild exportieren (.json)",
            Lang::ZH => "导出当前帧 (.json)",
            Lang::JA => "現在のフレームをエクスポート (.json)",
            Lang::PT => "Exportar quadro atual (.json)",
            Lang::VI => "Xuất khung hình hiện tại (.json)",
            Lang::NK => "Izvezi trenutni kadar (.json)",
        },
        Key::export_current_frame_png => match lang {
            Lang::EN => "Export current frame (.png)",
            Lang::ES => "Exportar cuadro actual (.png)",
            Lang::FR => "Exporter l'image actuelle (.png)",
            Lang::DE => "Aktuelles Bild exportieren (.png)",
            Lang::ZH => "导出当前帧 (.png)",
            Lang::JA => "現在のフレームをエクスポート (.png)",
            Lang::PT => "Exportar quadro atual (.png)",
            Lang::VI => "Xuất khung hình hiện tại (.png)",
            Lang::NK => "Izvezi trenutni kadar (.png)",
        },
        Key::frame_no_ai_data => match lang {
            Lang::EN => "This frame has no AI data",
            Lang::ES => "Este cuadro no tiene datos de IA",
            Lang::FR => "Cette image n'a pas de données IA",
            Lang::DE => "Dieses Bild hat keine KI-Daten",
            Lang::ZH => "此帧没有AI数据",
            Lang::JA => "このフレームにはAIデータがありません",
            Lang::PT => "Este quadro não tem dados de IA",
            Lang::VI => "Khung hình này không có dữ liệu AI",
            Lang::NK => "Ovaj kadar nema AI podatke",
        },
        Key::analyze_this_image => match lang {
            Lang::EN => "↻ Analyze this image",
            Lang::ES => "↻ Analizar esta imagen",
            Lang::FR => "↻ Analyser cette image",
            Lang::DE => "↻ Dieses Bild analysieren",
            Lang::ZH => "↻ 分析此图片",
            Lang::JA => "↻ この画像を解析",
            Lang::PT => "↻ Analisar esta imagem",
            Lang::VI => "↻ Xử lí hình ảnh này",
            Lang::NK => "↻ Analiziraj ovu sliku",
        },
        Key::analyze_this_image_hint => match lang {
            Lang::EN => "Run the selected AI on just this image. Useful for re-running with a different model.",
            Lang::ES => "Ejecutar la IA seleccionada solo en esta imagen. Útil para reejecutar con otro modelo.",
            Lang::FR => "Exécuter l'IA sélectionnée sur cette image uniquement. Utile pour relancer avec un autre modèle.",
            Lang::DE => "Die ausgewählte KI nur auf dieses Bild anwenden. Nützlich für eine neue Ausführung mit einem anderen Modell.",
            Lang::ZH => "仅对此图片运行所选AI。适合使用不同模型重新运行。",
            Lang::JA => "選択したAIをこの画像のみに実行します。別のモデルで再実行する際に便利です。",
            Lang::PT => "Executar a IA selecionada apenas nesta imagem. Útil para reexecutar com outro modelo.",
            Lang::VI => "Chạy AI đã chọn chỉ trên hình ảnh này. Hữu ích khi chạy lại với mô hình khác.",
            Lang::NK => "Pokreni odabrani AI samo na ovoj slici. Korisno za ponovno pokretanje s drugim modelom.",
        },
        Key::play => match lang {
            Lang::EN => "Play",
            Lang::ES => "Reproducir",
            Lang::FR => "Lecture",
            Lang::DE => "Wiedergabe",
            Lang::ZH => "播放",
            Lang::JA => "再生",
            Lang::PT => "Reproduzir",
            Lang::VI => "Phát",
            Lang::NK => "Pusti",
        },
        Key::frames_analysed => match lang {
            Lang::EN => "frames analysed",
            Lang::ES => "cuadros analizados",
            Lang::FR => "images analysées",
            Lang::DE => "Bilder analysiert",
            Lang::ZH => "已分析帧",
            Lang::JA => "フレーム解析済み",
            Lang::PT => "quadros analisados",
            Lang::VI => "khung hình đã phân tích",
            Lang::NK => "analiziranih kadrova",
        },
        Key::view_label => match lang {
            Lang::EN => "view",
            Lang::ES => "vista",
            Lang::FR => "vue",
            Lang::DE => "Ansicht",
            Lang::ZH => "视图",
            Lang::JA => "表示",
            Lang::PT => "vista",
            Lang::VI => "khung nhìn",
            Lang::NK => "prikaz",
        },
        Key::span_label => match lang {
            Lang::EN => "span",
            Lang::ES => "rango",
            Lang::FR => "intervalle",
            Lang::DE => "Bereich",
            Lang::ZH => "范围",
            Lang::JA => "範囲",
            Lang::PT => "intervalo",
            Lang::VI => "khoảng",
            Lang::NK => "raspon",
        },
        Key::buffer_label => match lang {
            Lang::EN => "buffer",
            Lang::ES => "búfer",
            Lang::FR => "tampon",
            Lang::DE => "Puffer",
            Lang::ZH => "缓冲",
            Lang::JA => "バッファ",
            Lang::PT => "buffer",
            Lang::VI => "bộ đệm",
            Lang::NK => "bafer",
        },
        Key::audio_processing => match lang {
            Lang::EN => "Audio processing",
            Lang::ES => "Procesamiento de audio",
            Lang::FR => "Traitement audio",
            Lang::DE => "Audioverarbeitung",
            Lang::ZH => "音频处理中",
            Lang::JA => "オーディオ処理中",
            Lang::PT => "Processando áudio",
            Lang::VI => "Xử lí âm thanh",
            Lang::NK => "Obrada zvuka",
        },
        Key::frame_label => match lang {
            Lang::EN => "frame",
            Lang::ES => "cuadro",
            Lang::FR => "image",
            Lang::DE => "Bild",
            Lang::ZH => "帧",
            Lang::JA => "フレーム",
            Lang::PT => "quadro",
            Lang::VI => "khung",
            Lang::NK => "kadar",
        },
    }
}
