#[derive(PartialEq)]
pub enum Lang {
    EN,
    ES,
    FR,
    DE,
    ZH,
    JA,
    PT,
    VI,
}

#[allow(non_camel_case_types)]
pub enum Key {
    select_ai,
    select_ep,
    setup,
    deploy,
    deployed_api,
    select_your_data,
    folder,
    image,
    video_file,
    camera_feed,
    about,
    idiom,
    models,
    donate,
    source_code,
    analyze,
    export,
    analysis,
    cancel,
    process_completed,
    done,
    error_ocurred,
    website,
    model_hub,
    api,
    image_processing,
    video_processing,
    feed_processing,
    model_hub_url,
    donate_url,
    website_url,
    export_predictions,
    export_imgs_with_predictions,
    copy_with_classification,
    input_url,
    example,
    freq,
    ok,
    no_predictions,
    add_classification_model_to_complement,
    configure_ai,
    confidence_level,
    overlap_filter,
    region_filter,
    select_architecture,
    model_have_no_architecture,
    yes,
    no_only_missing_data,
    process_everything,
    export_obs,
}

pub fn translate(key: Key, lang: &Lang) -> &'static str {
    match key {
        Key::select_ai => match lang {
            Lang::EN => "Select an AI",
            Lang::ES => "Selecciona una IA",
            Lang::FR => "Sélectionnez une IA",
            Lang::DE => "Wählen Sie eine KI aus",
            Lang::ZH => "选择AI模型",
            Lang::JA => "AIを選択",
            Lang::PT => "Selecionar uma IA",
            Lang::VI => "Lựa chọn AI",
        },
        Key::yes => match lang {
            Lang::EN => "Yes",
            Lang::ES => "Sí",
            Lang::FR => "Oui",
            Lang::DE => "Ja",
            Lang::ZH => "是",
            Lang::JA => "はい",
            Lang::PT => "Sim",
            Lang::VI => "Đồng ý",
        },
        Key::no_only_missing_data => match lang {
            Lang::EN => "No, only missing data",
            Lang::ES => "No, solo los datos faltantes",
            Lang::FR => "Non, seulement les données manquantes",
            Lang::DE => "Nein, nur fehlende Daten",
            Lang::ZH => "不，只处理缺失的数据",
            Lang::JA => "いいえ、不足しているデータのみ",
            Lang::PT => "Não, apenas os dados em falta",
            Lang::VI => "Không, chỉ khi dữ liệu bị thiếu",
        },
        Key::process_everything => match lang {
            Lang::EN => "Process everything?",
            Lang::ES => "¿Procesar todo?",
            Lang::FR => "Tout traiter ?",
            Lang::DE => "Alles verarbeiten?",
            Lang::ZH => "处理所有内容？",
            Lang::JA => "すべて処理しますか？",
            Lang::PT => "Processar tudo?",
            Lang::VI => "Xử lí mọi thứ?"
        },
        Key::select_architecture => match lang {
            Lang::VI => "Lựa chọn kiến trúc của mô hình",
            _ => "Select model architecture",
        },
        Key::model_have_no_architecture => match lang {
            Lang::VI => "Mô hình này không hỗ trợ kiến trúc được lựa chọn. Vui lòng chọn kiến trúc phù hợp:",
            _ => "This model doesn't have an architecture specified. Please select the appropriate architecture:",
        }
        Key::confidence_level => match lang {
            Lang::EN => "Confidence",
            Lang::ES => "Confianza",
            Lang::FR => "Confiance",
            Lang::DE => "Genauigkeit",
            Lang::ZH => "置信度",
            Lang::JA => "信頼度",
            Lang::PT => "Confiança",
            Lang::VI => "Độ tin cậy của mô hình"
        },
        Key::overlap_filter => match lang {
            Lang::EN => "Overlap Filter",
            Lang::ES => "Filtro de Solapamiento",
            Lang::FR => "Filtre de Chevauchement",
            Lang::DE => "Überlappungsfilter",
            Lang::ZH => "重叠过滤",
            Lang::JA => "重複フィルター",
            Lang::PT => "Filtro de Sobreposição",
            Lang::VI => "Bộ lọc trùng lặp",
        },
        Key::region_filter => match lang {
            Lang::EN => "Region (ISO 3166-1 alpha-3)",
            Lang::ES => "Región (ISO 3166-1 alpha-3)",
            Lang::FR => "Région (ISO 3166-1 alpha-3)",
            Lang::DE => "Region (ISO 3166-1 alpha-3)",
            Lang::ZH => "区域 (ISO 3166-1 alpha-3)",
            Lang::JA => "地域 (ISO 3166-1 alpha-3)",
            Lang::PT => "Região (ISO 3166-1 alpha-3)",
            Lang::VI => "Mã quốc gia (ISO 3166-1 alpha-3)",
        },
        Key::configure_ai => match lang {
            Lang::EN => "Configure AI",
            Lang::ES => "Configurar IA",
            Lang::FR => "Configurer l'IA",
            Lang::DE => "KI konfigurieren",
            Lang::ZH => "配置AI",
            Lang::JA => "AIを設定",
            Lang::PT => "Configurar IA",
            Lang::VI => "Cấu hình AI"
        },
        Key::add_classification_model_to_complement => match lang {
            Lang::EN => "Add a classification AI to complement the current model",
            Lang::ES => "Agregar una IA de clasificación para complementar el modelo actual",
            Lang::FR => "Ajouter une IA de classification pour compléter le modèle actuel",
            Lang::DE => "Eine Klassifikations-KI hinzufügen, um das aktuelle Modell zu ergänzen",
            Lang::ZH => "添加分类AI以补充当前模型",
            Lang::JA => "現在のモデルを補完する分類AIを追加",
            Lang::PT => "Adicionar uma IA de classificação para complementar o modelo atual",
            Lang::VI => "Bổ sung một mô hình AI phân loại để hỗ trợ mô hình hiện tại"
        },
        Key::select_ep => match lang {
            Lang::EN => "Select a processor",
            Lang::ES => "Selecciona un procesador",
            Lang::FR => "Sélectionnez un processeur",
            Lang::DE => "Wählen Sie einen Prozessor aus",
            Lang::ZH => "选择处理器",
            Lang::JA => "プロセッサーを選択",
            Lang::PT => "Selecionar um processador",
            Lang::VI => "Chọn bộ xử lí",
        },
        Key::setup => match lang {
            Lang::EN => "Setup",
            Lang::ES => "Configuración",
            Lang::FR => "Configuration",
            Lang::DE => "Einrichtung",
            Lang::ZH => "配置",
            Lang::JA => "セットアップ",
            Lang::PT => "Configuração",
            Lang::VI => "Thiết lập mô hình",
        },
        Key::no_predictions => match lang {
            Lang::EN => "No predictions",
            Lang::ES => "Sin predicciones",
            Lang::FR => "Aucune prédiction",
            Lang::DE => "Keine Vorhersagen",
            Lang::ZH => "没有预测",
            Lang::JA => "予測なし",
            Lang::PT => "Sem previsões",
            Lang::VI => "Không tìm thấy kết quả dự đoán"
        },
        Key::deploy => match lang {
            Lang::EN => "Deploy",
            Lang::ES => "Desplegar",
            Lang::FR => "Déployer",
            Lang::DE => "Bereitstellen",
            Lang::ZH => "部署",
            Lang::JA => "デプロイ",
            Lang::PT => "Implantar",
            Lang::VI => "Triển khai"
        },
        Key::deployed_api => match lang {
            Lang::EN => "Deployed API",
            Lang::ES => "API desplegada",
            Lang::FR => "API déployée",
            Lang::DE => "Bereitgestellte API",
            Lang::ZH => "已部署API",
            Lang::JA => "デプロイ済みAPI",
            Lang::PT => "API implantada",
            Lang::VI => "Triển khai API"
        },
        Key::select_your_data => match lang {
            Lang::EN => "Select your data",
            Lang::ES => "Selecciona tus datos",
            Lang::FR => "Sélectionnez vos données",
            Lang::DE => "Wählen Sie Ihre Daten aus",
            Lang::ZH => "选取数据",
            Lang::JA => "データを選択",
            Lang::PT => "Selecionar os seus dados",
            Lang::VI => "Chọn dữ liệu của bạn"
        },
        Key::folder => match lang {
            Lang::EN => "Folder",
            Lang::ES => "Carpeta",
            Lang::FR => "Dossier",
            Lang::DE => "Ordner",
            Lang::ZH => "文件夹",
            Lang::JA => "フォルダ",
            Lang::PT => "Pasta",
            Lang::VI => "Thư mục"
        },
        Key::image => match lang {
            Lang::EN => "Image",
            Lang::ES => "Imagen",
            Lang::FR => "Image",
            Lang::DE => "Bild",
            Lang::ZH => "图片",
            Lang::JA => "画像",
            Lang::PT => "Imagem",
            Lang::VI => "Hình ảnh"
        },
        Key::video_file => match lang {
            Lang::EN => "Video",
            Lang::ES => "Video",
            Lang::FR => "Vidéo",
            Lang::DE => "Video",
            Lang::ZH => "视频",
            Lang::JA => "ビデオ",
            Lang::PT => "Vídeo",
            Lang::VI => "Video"
        },
        Key::camera_feed => match lang {
            Lang::EN => "Feed",
            Lang::ES => "Cámara",
            Lang::FR => "Flux",
            Lang::DE => "Kamerafeed",
            Lang::ZH => "视频流",
            Lang::JA => "カメラフィード",
            Lang::PT => "Transmissão",
            Lang::VI => "Nguồn khác"
        },
        Key::about => match lang {
            Lang::EN => "About",
            Lang::ES => "Información",
            Lang::FR => "À propos",
            Lang::DE => "Über",
            Lang::ZH => "关于",
            Lang::JA => "情報",
            Lang::PT => "Sobre",
            Lang::VI => "Thông tin"
        },
        Key::idiom => match lang {
            Lang::EN => "Language",
            Lang::ES => "Idioma",
            Lang::FR => "Langue",
            Lang::DE => "Sprache",
            Lang::ZH => "语言",
            Lang::JA => "言語",
            Lang::PT => "Idioma",
            Lang::VI => "Ngôn ngữ"
        },
        Key::models => match lang {
            Lang::EN => "Models",
            Lang::ES => "Modelos",
            Lang::FR => "Modèles",
            Lang::DE => "Modelle",
            Lang::ZH => "模型",
            Lang::JA => "モデル",
            Lang::PT => "Modelos",
            Lang::VI => "Mô hình"
        },
        Key::donate => match lang {
            Lang::EN => "Donate",
            Lang::ES => "Donar",
            Lang::FR => "Faire un don",
            Lang::DE => "Spenden",
            Lang::ZH => "捐助",
            Lang::JA => "寄付する",
            Lang::PT => "Doar",
            Lang::VI => "Ủng hộ"
        },
        Key::source_code => match lang {
            Lang::EN => "Source code",
            Lang::ES => "Código fuente",
            Lang::FR => "Code source",
            Lang::DE => "Quellcode",
            Lang::ZH => "源代码",
            Lang::JA => "ソースコード",
            Lang::PT => "Código-fonte",
            Lang::VI => "Mã nguồn"
        },
        Key::analyze => match lang {
            Lang::EN => "Analyze",
            Lang::ES => "Analizar",
            Lang::FR => "Analyser",
            Lang::DE => "Analysieren",
            Lang::ZH => "开始分析",
            Lang::JA => "解析する",
            Lang::PT => "Analisar",
            Lang::VI => "Xử lí"
        },
        Key::export => match lang {
            Lang::EN => "Export",
            Lang::ES => "Exportar",
            Lang::FR => "Exporter",
            Lang::DE => "Exportieren",
            Lang::ZH => "导出",
            Lang::JA => "エクスポート",
            Lang::PT => "Exportar",
            Lang::VI => "Xuất kết quả"
        },
        Key::analysis => match lang {
            Lang::EN => "Analysis",
            Lang::ES => "Análisis",
            Lang::FR => "Analyse",
            Lang::DE => "Analyse",
            Lang::ZH => "分析",
            Lang::JA => "解析",
            Lang::PT => "Análise",
            Lang::VI => "Phân tích"
        },
        Key::cancel => match lang {
            Lang::EN => "Cancel",
            Lang::ES => "Cancelar",
            Lang::FR => "Annuler",
            Lang::DE => "Abbrechen",
            Lang::ZH => "取消",
            Lang::JA => "キャンセル",
            Lang::PT => "Cancelar",
            Lang::VI => "Hủy bỏ"
        },
        Key::ok => match lang {
            Lang::EN => "OK",
            Lang::ES => "Aceptar",
            Lang::FR => "OK",
            Lang::DE => "OK",
            Lang::ZH => "确定",
            Lang::JA => "OK",
            Lang::PT => "OK",
            Lang::VI => "Hủy bỏ"
        },
        Key::process_completed => match lang {
            Lang::EN => "Process completed",
            Lang::ES => "Proceso completado",
            Lang::FR => "Processus terminé",
            Lang::DE => "Prozess abgeschlossen",
            Lang::ZH => "处理完成",
            Lang::JA => "処理完了",
            Lang::PT => "Processo concluído",
            Lang::VI => "Tiến trình đã hoàn tất"
        },
        Key::done => match lang {
            Lang::EN => "✅ Done",
            Lang::ES => "✅ Listo",
            Lang::FR => "✅ Terminé",
            Lang::DE => "✅ Fertig",
            Lang::ZH => "✅ 已完成",
            Lang::JA => "✅ 完了",
            Lang::PT => "✅ Concluído",
            Lang::VI => "✅ Hoàn tất"
        },
        Key::error_ocurred => match lang {
            Lang::EN => "Error occurred",
            Lang::ES => "Ocurrió un error",
            Lang::FR => "Une erreur est survenue",
            Lang::DE => "Ein Fehler ist aufgetreten",
            Lang::ZH => "发生错误",
            Lang::JA => "エラーが発生しました",
            Lang::PT => "Ocorreu um erro",
            Lang::VI => "Đã có lỗi xảy ra"
        },
        Key::website => match lang {
            Lang::EN => "Website",
            Lang::ES => "Sitio web",
            Lang::FR => "Site web",
            Lang::DE => "Website",
            Lang::ZH => "网站",
            Lang::JA => "ウェブサイト",
            Lang::PT => "Website",
            Lang::VI => "Trang web"
        },
        Key::model_hub => match lang {
            Lang::EN => "Model HUB",
            Lang::ES => "HUB de Modelos",
            Lang::FR => "HUB de Modèles",
            Lang::DE => "Modell-HUB",
            Lang::ZH => "模型库",
            Lang::JA => "モデルハブ",
            Lang::PT => "Central de Modelos",
            Lang::VI => "Model Hub",
        },
        Key::api => match lang {
            _ => "API",
        },
        Key::image_processing => match lang {
            Lang::EN => "Images processing",
            Lang::ES => "Procesamiento de imágenes",
            Lang::FR => "Traitement d'images",
            Lang::DE => "Bildverarbeitung",
            Lang::ZH => "图片处理中",
            Lang::JA => "画像を処理中",
            Lang::PT => "Processando imagens",
            Lang::VI => "Xử lí hình ảnh"
        },
        Key::video_processing => match lang {
            Lang::EN => "Video processing",
            Lang::ES => "Procesamiento de video",
            Lang::FR => "Traitement vidéo",
            Lang::DE => "Videoverarbeitung",
            Lang::ZH => "视频处理中",
            Lang::JA => "ビデオ処理中",
            Lang::PT => "Processando vídeo",
            Lang::VI => "Xử lí video"
        },
        Key::feed_processing => match lang {
            Lang::EN => "Feed processing",
            Lang::ES => "Procesamiento en vivo",
            Lang::FR => "Traitement en direct",
            Lang::DE => "Live-Verarbeitung",
            Lang::ZH => "视频流处理中",
            Lang::JA => "フィード処理中",
            Lang::PT => "Processando transmissão",
            Lang::VI => "Xử lí dữ liệu khác"
        },
        Key::model_hub_url => match lang {
            Lang::EN => "https://boquila.org/hub",
            Lang::ES => "https://boquila.org/es/hub",
            Lang::FR => "https://boquila.org/fr/hub",
            Lang::DE => "https://boquila.org/de/hub",
            Lang::ZH => "https://boquila.org/zh/hub",
            Lang::JA => "https://boquila.org/jp/hub",
            _ => "https://boquila.org/hub",
        },
        Key::website_url => match lang {
            Lang::EN => "https://boquila.org/en",
            Lang::ES => "https://boquila.org/",
            Lang::FR => "https://boquila.org/fr",
            Lang::DE => "https://boquila.org/de",
            Lang::ZH => "https://boquila.org/zh",
            Lang::JA => "https://boquila.org/jp",
            _ => "https://boquila.org/en",
        },
        Key::donate_url => match lang {
            Lang::EN => "https://boquila.org/donate",
            Lang::ES => "https://boquila.org/donar",
            Lang::FR => "https://boquila.org/fr/donate",
            Lang::DE => "https://boquila.org/spenden",
            Lang::ZH => "https://boquila.org/zh/donate",
            Lang::JA => "https://boquila.org/jp/donate",
            _ => "https://boquila.org/donate",
        },
        Key::export_predictions => match lang {
            Lang::EN => "Export predictions (.json)",
            Lang::ES => "Exportar predicciones (.json)",
            Lang::FR => "Exporter les prédictions (.json)",
            Lang::DE => "Vorhersagen exportieren (.json)",
            Lang::ZH => "导出识别结果（.json）",
            Lang::JA => "予測をエクスポート（.json）",
            Lang::PT => "Exportar previsões (.json)",
            Lang::VI => "Xuất kết quả (.json)"
        },
        Key::export_imgs_with_predictions => match lang {
            Lang::EN => "Export images with predictions (.jpg)",
            Lang::ES => "Exportar imágenes con predicciones (.jpg)",
            Lang::FR => "Exporter les images avec prédictions (.jpg)",
            Lang::DE => "Bilder mit Vorhersagen exportieren (.jpg)",
            Lang::ZH => "导出含识别结果的图片（.jpg）",
            Lang::JA => "予測付き画像をエクスポート（.jpg）",
            Lang::PT => "Exportar imagens com previsões (.jpg)",
            Lang::VI => "Xuất kết quả (.jpg)"
        },
        Key::copy_with_classification => match lang {
            Lang::EN => "Copy and separate in folders according to classification",
            Lang::ES => "Copiar y separar en carpetas según clasificación",
            Lang::FR => "Copier et séparer dans des dossiers selon la classification",
            Lang::DE => "Kopieren und nach Klassifizierung in Ordner trennen",
            Lang::ZH => "根据结果将数据复制到不同文件夹",
            Lang::JA => "分類に応じてフォルダにコピー・振り分け",
            Lang::PT => "Copiar e separar em pastas por classificação",
            Lang::VI => "Sao chép và phân loại theo từng thu mục"
        },
        Key::input_url => match lang {
            Lang::EN => "Add the URL",
            Lang::ES => "Ingresa la dirección URL",
            Lang::FR => "Ajoutez l'URL",
            Lang::DE => "URL hinzufügen",
            Lang::ZH => "输入视频流地址（URL）",
            Lang::JA => "URLを追加",
            Lang::PT => "Adicionar o URL",
            Lang::VI => "Nhập URL"
        },
        Key::example => match lang {
            Lang::EN => "Example",
            Lang::ES => "Ejemplo",
            Lang::FR => "Exemple",
            Lang::DE => "Beispiel",
            Lang::ZH => "示例",
            Lang::JA => "例",
            Lang::PT => "Exemplo",
            Lang::VI => "Mẫu"
        },
        Key::freq => match lang {
            Lang::EN => "Frequency",
            Lang::ES => "Frecuencia",
            Lang::FR => "Fréquence",
            Lang::DE => "Frequenz",
            Lang::ZH => "频率",
            Lang::JA => "頻度",
            Lang::PT => "Frequência",
            Lang::VI => "Tần suất"
        },
        Key::export_obs => match lang {
            Lang::EN => "Export detections",
            Lang::ES => "Exportar detecciones",
            Lang::FR => "Exporter détections", 
            Lang::DE => "Erkennungen exportieren",
            Lang::ZH => "导出检测",
            Lang::JA => "検出をエクスポート",
            Lang::PT => "Exportar detecções",
            Lang::VI => "Trích xuất kết quả phát hiện"
        },
    }
}

pub fn get_locale() -> Lang {
    let locale = sys_locale::get_locale().unwrap_or_else(|| "en-US".to_owned());
    let lang_code = locale.get(0..2).unwrap_or("en").to_lowercase();
    match lang_code.as_str() {
        "en" => Lang::EN,
        "es" => Lang::ES,
        "fr" => Lang::FR,
        "de" => Lang::DE,
        "zh" => Lang::ZH,
        "ja" => Lang::JA,
        "pt" => Lang::PT,
        "vi" => Lang::VI,
        _ => Lang::EN,
    }
}
