name: Build and Test Run on Linux

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            libavutil-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libavdevice-dev \
            libavfilter-dev \
            libswresample-dev
            
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test -- --nocapture

      - name: Run for at least 10 seconds
        run: |
          cargo run &
          PID=$!
          sleep 15
          if ! kill -0 $PID 2>/dev/null; then
            wait $PID
            exit $?
          fi
          kill $PID
