name: Build and Test Run on Windows

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download FFmpeg
        run: |
          curl -L -o ffmpeg.7z https://github.com/GyanD/codexffmpeg/releases/download/7.1.1/ffmpeg-7.1.1-full_build-shared.7z
          7z x ffmpeg.7z -offmpeg -y

      - name: Set FFMPEG_DIR and PATH
        run: |
          echo "FFMPEG_DIR=${{ github.workspace }}\ffmpeg\ffmpeg-7.1.1-full_build-shared" >> $env:GITHUB_ENV
          echo "${{ github.workspace }}\ffmpeg\ffmpeg-7.1.1-full_build-shared\bin" >> $env:GITHUB_PATH

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test -- --nocapture

      - name: Run for at least 10 seconds
        shell: pwsh
        run: |
          $proc = Start-Process -NoNewWindow -FilePath cargo -ArgumentList "run" -PassThru
          Start-Sleep -Seconds 10
          if ($proc.HasExited) {
            exit $proc.ExitCode
          }
          Stop-Process -Id $proc.Id -Force
